sudo: required
services:
  - docker
before_install: 
  - docker build -t abhinav/react-test -f ./client/Dockerfile.dev ./client
script: 
  - "docker run abhinav/react-test npm test -- --coverage"
after_success: 
  - docker build -t abhinav/multi-client ./client
  - docker build -t abhinav/multi-nginx ./nginx
  - docker build -t abhinav/multi-server ./server
  - docker build -t abhinav/multi-worker ./worker
# login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "abhinav1710" --password-stdin
  - docker push abhinav1710/abhinav/multi-client
  - docker push abhinav1710/abhinav/multi-nginx
  - docker push abhinav1710/abhinav/multi-server
  - docker push abhinav1710/abhinav/multi-worker
